// Project-folder copies and the revision log.
//
// A job's "File location" is its project folder on the network share. The
// board keeps two things there up to date, and nothing else:
//   <folder>/BoardReview/<JOB>/<drawing>/attempt <n>.pdf      submitted PDFs under review
//   <folder>/BoardReview/<JOB>/<drawing> - board reviewed (attempt <n>).pdf
//                                                             the exact PDF that passed
//   <folder>/REVISION_LOG.md                                  generated from board history
//
// Rules (decision #26):
//   * The board only replaces or deletes a file it wrote itself (recorded in
//     project_files) and only while its content is still what the board wrote.
//     Anything else with the same name is left alone and reported.
//   * Signed scans, CAD files and every other file in the folder are never
//     written, moved or deleted. Signed scans are not even copied here.
//   * The share may be offline: the board's own storage stays the source of
//     truth, and the copies are retried until they succeed.

import { createHash } from 'node:crypto';
import { copyFile, mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { DRAWING_STATE_LABEL, type ReviewWorkspace } from '@board/shared';
import { all, get, run } from '../db/connection.ts';
import { nowIso } from '../lib/core.ts';
import { blobPath, hasBlob, type StoreCtx } from './reviewStore.ts';
import { workspace, localDay } from './reviews.ts';
import { getUser } from './users.ts';

const LOG_NAME = 'REVISION_LOG.md';
export const folderKey = (folder: string) => folder.trim().replace(/[\\/]+$/, '').toLowerCase();
const safeName = (s: string) => s.replace(/[\\/:*?"<>|\u0000-\u001f]/g, '_').replace(/[. ]+$/, '').slice(0, 120) || '_';

export function reviewedName(identifier: string, attempt: number) {
  return `${safeName(identifier)} - board reviewed (attempt ${attempt}).pdf`;
}

function setSync(ctx: StoreCtx, ticketId: number, state: 'ok' | 'pending' | 'failed' | 'no_folder', detail: string | null) {
  run(
    ctx.db,
    `INSERT INTO review_sync (ticket_id, state, detail, updated_at) VALUES (?, ?, ?, ?)
     ON CONFLICT(ticket_id) DO UPDATE SET state = excluded.state, detail = excluded.detail, updated_at = excluded.updated_at`,
    ticketId,
    state,
    detail,
    nowIso(ctx),
  );
  ctx.events.emit({ type: 'ticket', id: ticketId, by: null });
  ctx.events.flush();
}

/** Mark a job's copies as needing an update (shown until the next sync finishes). */
export function markSyncPending(ctx: StoreCtx, ticketId: number) {
  const folder = get<{ file_location: string }>(ctx.db, 'SELECT file_location FROM tickets WHERE id = ?', ticketId)?.file_location ?? '';
  run(
    ctx.db,
    `INSERT INTO review_sync (ticket_id, state, detail, updated_at) VALUES (?, ?, NULL, ?)
     ON CONFLICT(ticket_id) DO UPDATE SET state = excluded.state, detail = NULL, updated_at = excluded.updated_at`,
    ticketId,
    folder.trim() ? 'pending' : 'no_folder',
    nowIso(ctx),
  );
}

const sha256 = (b: Buffer | string) => createHash('sha256').update(b).digest('hex');
async function fileSha(path: string): Promise<string | null> {
  try {
    return sha256(await readFile(path));
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw e;
  }
}

// ---------------------------------------------------------------------------
// Revision log
// ---------------------------------------------------------------------------

/** The REVISION_LOG.md text for every job whose File location is `folder`. */
export function revisionLog(ctx: StoreCtx, folder: string, onlyTicket?: number): string {
  const key = folderKey(folder);
  const ids = onlyTicket
    ? [onlyTicket]
    : all<{ id: number; file_location: string }>(
        ctx.db,
        `SELECT DISTINCT t.id, t.file_location FROM tickets t JOIN review_drawings d ON d.ticket_id = t.id ORDER BY t.job_number`,
      )
        .filter((r) => folderKey(r.file_location) === key)
        .map((r) => r.id);
  const name = (id: number | null) => (id == null ? 'the board' : getUser(ctx, id)?.name ?? `user #${id}`);
  const when = (iso: string | null) =>
    iso
      ? `${localDay(ctx, iso)} ${new Intl.DateTimeFormat('en-GB', { timeZone: ctx.tz, hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(iso))}`
      : '';
  const oneLine = (s: string | null | undefined) => (s ?? '').replace(/\r?\n+/g, ' ').trim();
  const lines: string[] = [
    '# Revision log',
    '',
    `Generated by Engineering Board from its review history. Do not edit: the board rewrites this file. Last updated ${when(nowIso(ctx))}.`,
    '',
    '> Board review is an internal check. It is **not** official approval: the physically signed drawing is the approved record, and the signed scans in this folder remain the official reference.',
    '',
  ];
  for (const id of ids) {
    const w: ReviewWorkspace = workspace(ctx, id);
    const t = w.ticket;
    lines.push(`## ${t.job_number} · ${oneLine(t.title)}`, '');
    if (w.references.length)
      lines.push(`Signed reference scans: ${w.references.map((r) => `${r.filename} (${r.pages} pages, attached ${localDay(ctx, r.attached_at)} by ${name(r.attached_by)})`).join('; ')}`, '');
    for (const d of w.drawings) {
      lines.push(`### ${d.identifier} · ${d.kind === 'new' ? 'new drawing' : 'revision'} · ${DRAWING_STATE_LABEL[d.state]}`, '');
      if (d.ref_page && d.ref_reference_id) {
        const r = w.references.find((x) => x.id === d.ref_reference_id);
        if (r) lines.push(`- Reference page: page ${d.ref_page} of ${r.filename}`);
      }
      for (const a of d.attempts) {
        lines.push(`- **Attempt ${a.number}** · ${a.filename} · submitted by ${name(a.submitted_by)}, ${when(a.submitted_at)} (submission ${a.submission_number})`);
        lines.push(`  - ${d.kind === 'new' && a.number === 1 ? 'Purpose' : 'What changed and why'}: ${oneLine(a.notes)}`);
        for (const c of d.comments.filter((c) => c.attempt_id === a.id)) {
          lines.push(`  - Comment by ${name(c.user_id)}, ${when(c.created_at)}: ${oneLine(c.body)}`);
          if (c.response) lines.push(`    - Correction response by ${name(c.response_by)}, ${when(c.response_at)}: ${oneLine(c.response)}`);
          if (c.resolved_at) lines.push(`    - Resolved by ${name(c.resolved_by)}, ${when(c.resolved_at)}`);
        }
        if (a.outcome === 'passed')
          lines.push(`  - Outcome: board review passed by ${name(a.decided_by)}, ${when(a.decided_at)}${a.decision_note ? `: ${oneLine(a.decision_note)}` : ''} (internal review, not official approval)`);
        else if (a.outcome === 'returned')
          lines.push(`  - Outcome: returned for correction by ${name(a.decided_by)}, ${when(a.decided_at)}${a.decision_note ? `: ${oneLine(a.decision_note)}` : ''}`);
        else if (a.outcome === 'superseded') lines.push(`  - Outcome: replaced by a newer attempt before a decision`);
        else lines.push(`  - Outcome: awaiting board review`);
        if (a.file_removed_at) lines.push(`  - Intermediate PDF removed after board review (${localDay(ctx, a.file_removed_at)})`);
        else if (a.id === d.passed_attempt_id) lines.push(`  - Kept as the reviewed PDF: BoardReview/${t.job_number}/${reviewedName(d.identifier, a.number)}`);
      }
      if (d.handover_at) lines.push(`- Handed over for signature: ${when(d.handover_at)}, recorded by ${name(d.handover_by)}; ${name(d.passed_by)} reminded`);
      if (d.signed_at) lines.push(`- Physically signed: recorded ${when(d.signed_at)} by ${name(d.signed_by)}`);
      for (const e of w.events.filter((e) => e.drawing_id === d.id && ['withdrawn', 'renamed'].includes(e.kind)))
        lines.push(`- ${e.kind === 'withdrawn' ? 'Withdrawn' : 'Number corrected'}: ${when(e.at)} by ${name(e.user_id)}${e.detail ? `: ${oneLine(e.detail)}` : ''}`);
      if (d.cleanup !== 'none')
        lines.push(
          `- Intermediate-file clean-up: ${d.cleanup === 'done' ? 'done' : d.cleanup === 'pending' ? 'pending' : `failed, will retry (${oneLine(d.cleanup_detail)})`}`,
        );
      lines.push('');
    }
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Sync
// ---------------------------------------------------------------------------

const queues = new Map<string, Promise<unknown>>();

/** Bring a job's project-folder copies up to date. Runs one at a time per folder. */
export function syncProjectFolder(ctx: StoreCtx, ticketId: number): Promise<void> {
  const folder = get<{ file_location: string }>(ctx.db, 'SELECT file_location FROM tickets WHERE id = ?', ticketId)?.file_location ?? '';
  const key = folderKey(folder) || `#${ticketId}`;
  const prev = queues.get(key) ?? Promise.resolve();
  const next = prev.then(() => doSync(ctx, ticketId)).catch((e) => {
    try {
      setSync(ctx, ticketId, 'failed', (e as Error).message);
    } catch {
      /* database closed (shutdown) */
    }
  });
  queues.set(key, next);
  void next.finally(() => {
    if (queues.get(key) === next) queues.delete(key);
  });
  return next;
}

/** Wait for every queued folder update (tests and shutdown). */
export async function settleSyncs() {
  while (queues.size) await Promise.all([...queues.values()]);
}

async function doSync(ctx: StoreCtx, ticketId: number): Promise<void> {
  if (!ctx.db.isOpen) return;
  const t = get<{ job_number: string; file_location: string }>(ctx.db, 'SELECT job_number, file_location FROM tickets WHERE id = ?', ticketId);
  if (!t) return;
  // nothing to copy yet (only a signed scan attached): scans are never copied
  if (!get(ctx.db, 'SELECT 1 FROM review_drawings WHERE ticket_id = ?', ticketId)) return setSync(ctx, ticketId, 'ok', null);
  const folder = t.file_location.trim();
  if (!folder) return setSync(ctx, ticketId, 'no_folder', 'Set the job\'s File location to its project folder to keep copies and the revision log there.');
  const root = resolve(folder);
  try {
    const st = await stat(root);
    if (!st.isDirectory()) throw new Error('not a folder');
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    return setSync(ctx, ticketId, 'failed', `Can't reach the project folder ${folder} (${code ?? (e as Error).message}). The board keeps its own copies and will try again.`);
  }
  const key = folderKey(folder);
  const inside = (p: string) => {
    const full = resolve(p);
    if (!full.startsWith(root + sep)) throw new Error(`refusing to write outside the project folder: ${p}`);
    return full;
  };

  // what should be there
  const desired = new Map<string, { sha: string; source: string | Buffer }>();
  const job = safeName(t.job_number);
  const drawings = all<{ id: number; identifier: string; passed_attempt_id: number | null; state: string }>(
    ctx.db,
    'SELECT id, identifier, passed_attempt_id, state FROM review_drawings WHERE ticket_id = ?',
    ticketId,
  );
  const problems: string[] = [];
  for (const d of drawings) {
    const attempts = all<{ id: number; number: number; sha256: string; file_removed_at: string | null }>(
      ctx.db,
      'SELECT id, number, sha256, file_removed_at FROM review_attempts WHERE drawing_id = ?',
      d.id,
    );
    for (const a of attempts) {
      if (a.file_removed_at) continue;
      const isFinal = a.id === d.passed_attempt_id && ['passed', 'handed_over', 'signed'].includes(d.state);
      const rel = isFinal ? ['BoardReview', job, reviewedName(d.identifier, a.number)] : ['BoardReview', job, safeName(d.identifier), `attempt ${a.number}.pdf`];
      if (!hasBlob(ctx, a.sha256)) {
        problems.push(`${d.identifier} attempt ${a.number}: the board's copy is missing`);
        continue;
      }
      desired.set(rel.join('/'), { sha: a.sha256, source: blobPath(ctx, a.sha256) });
    }
  }
  const log = Buffer.from(revisionLog(ctx, folder), 'utf8');
  const logSha = sha256(log);

  const recorded = all<{ id: number; path: string; sha256: string; ticket_id: number | null; removed_at: string | null }>(
    ctx.db,
    'SELECT id, path, sha256, ticket_id, removed_at FROM project_files WHERE folder = ?',
    key,
  );
  const byPath = new Map(recorded.map((r) => [r.path, r]));
  const record = (path: string, sha: string) =>
    run(
      ctx.db,
      `INSERT INTO project_files (folder, path, ticket_id, sha256, written_at) VALUES (?, ?, ?, ?, ?)
       ON CONFLICT(folder, path) DO UPDATE SET sha256 = excluded.sha256, ticket_id = excluded.ticket_id, written_at = excluded.written_at, removed_at = NULL`,
      key,
      path,
      path === LOG_NAME ? null : ticketId,
      sha,
      nowIso(ctx),
    );

  // 1. copies of PDFs under review and the reviewed finals
  for (const [rel, want] of desired) {
    const target = inside(join(root, ...rel.split('/')));
    try {
      const have = await fileSha(target);
      if (have === want.sha) {
        if (byPath.get(rel)?.sha256 !== want.sha || byPath.get(rel)?.removed_at) record(rel, want.sha);
        continue;
      }
      if (have != null) {
        const mine = byPath.get(rel);
        if (!mine || mine.removed_at || mine.sha256 !== have) {
          problems.push(`${rel} already exists and was not written by the board, so it was left alone`);
          continue;
        }
      }
      await mkdir(resolve(target, '..'), { recursive: true });
      const tmp = `${target}.board-partial`;
      await copyFile(want.source as string, tmp);
      if ((await fileSha(tmp)) !== want.sha) {
        await rm(tmp, { force: true });
        throw new Error('the copy did not match the board\'s file');
      }
      await rename(tmp, target);
      record(rel, want.sha);
    } catch (e) {
      problems.push(`${rel}: ${(e as NodeJS.ErrnoException).code ?? (e as Error).message}`);
    }
  }

  // 2. remove copies of intermediate PDFs the board wrote and no longer needs
  for (const r of recorded) {
    if (r.removed_at || r.ticket_id !== ticketId || r.path === LOG_NAME || desired.has(r.path)) continue;
    const target = inside(join(root, ...r.path.split('/')));
    try {
      const have = await fileSha(target);
      if (have == null || have === r.sha256) {
        if (have != null) await rm(target, { force: true });
        run(ctx.db, 'UPDATE project_files SET removed_at = ? WHERE id = ?', nowIso(ctx), r.id);
      } else problems.push(`${r.path} was changed after the board wrote it, so it was not removed`);
    } catch (e) {
      problems.push(`removing ${r.path}: ${(e as NodeJS.ErrnoException).code ?? (e as Error).message}`);
    }
  }

  // 3. the revision log
  const logPath = inside(join(root, LOG_NAME));
  try {
    const have = await fileSha(logPath);
    const mine = byPath.get(LOG_NAME);
    if (have !== logSha) {
      if (have != null && (!mine || mine.sha256 !== have)) {
        problems.push(`${LOG_NAME} exists but was not written by the board (or was edited), so it was not replaced. Rename it to let the board write its log.`);
      } else {
        const tmp = `${logPath}.board-partial`;
        await writeFile(tmp, log);
        await rename(tmp, logPath);
        record(LOG_NAME, logSha);
      }
    }
  } catch (e) {
    problems.push(`${LOG_NAME}: ${(e as NodeJS.ErrnoException).code ?? (e as Error).message}`);
  }

  setSync(ctx, ticketId, problems.length ? 'failed' : 'ok', problems.length ? problems.join('; ') : null);
}

/** Jobs whose copies are pending or failed (retried by maintenance). */
export function jobsNeedingSync(ctx: StoreCtx): number[] {
  return all<{ ticket_id: number }>(ctx.db, `SELECT ticket_id FROM review_sync WHERE state IN ('pending','failed')`).map((r) => r.ticket_id);
}
